Base modifications after fork.
MULTIVAC-SE/terraform-azurerm-virtual-machine pull request #1
Opened 2021-05-25 09:11 UTC by schauppm

- Corrected CRLF
- Replace linux ssh_key reference from file to key itself
- Refactor to take different resource groups for vnets and vms into account
- Add 2nd gen Windows Server OS version

Serves as base vor Release 0.1.0

2021-05-27 05:58 UTC, fmayerhof approved these changes

2021-06-07 11:36 UTC, claudiuskastner requested changes

2021-06-07 11:36 UTC, claudiuskastner commented on .pre-commit-config.yaml
> +  rev: v1.30.0
Update fehlt hier noch .. müsste eigentlich v1.50.0 sein glaube ich

2021-06-07 11:40 UTC, schauppm commented on .pre-commit-config.yaml
> +  rev: v1.30.0
Hab eigentlich nen neueren commit wo dasupgedated wurde

2021-06-07 12:39 UTC, claudiuskastner approved these changes

2021-06-07 13:27 UTC, merged